### PR TITLE
Share API

### PR DESCRIPTION
**Pull request by h44z**
Hi,

I have implemented some functions for "Link-Shares". Listing shares, creating and deleting is implemented.

### CODE REVIEW

**Comment by rene-s** [comment]
Hello, thanks for the pull request. Please separate the new code for the Share resource from the fopen() issue in the File resource so I can merge the new code, thank you.

Regards 
Rene

**Comment by h44z** [comment]
HI,

I am getting following error when I use it the without the fopen(..., "w"):

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to open C:\Users\h44z\Downloads\seaf-php\seaf-php\test\DL_1449502425.txt using mode r+: fopen(C:\Users\h44z\Downloads\seaf-php\seaf-php\test\DL_1449502425.txt): failed to open stream: No such file or directory' in C:\Users\h44z\Downloads\seaf-php\seaf-php\vendor\guzzlehttp\psr7\src\functions.php:275
Stack trace:
#0 [internal function]: GuzzleHttp\Psr7\{closure}(2, 'fopen(C:\\Users\\...', 'C:\\Users\\h44z\\D...', 283, Array)
#1 C:\Users\h44z\Downloads\seaf-php\seaf-php\vendor\guzzlehttp\psr7\src\functions.php(283): fopen('C:\\Users\\h44z\\D...', 'r+')
#2 C:\Users\h44z\Downloads\seaf-php\seaf-php\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(141): GuzzleHttp\Psr7\try_fopen('C:\\Users\\h44z\\D...', 'r+')
#3 C:\Users\h44z\Downloads\seaf-php\seaf-php\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(108): GuzzleHttp\Handler\StreamHandler->createSink(Object(GuzzleHttp\Psr7\Stream), Array)
#4 C:\Users\h44z\Downloads\seaf-php\seaf-php\vendor\guz in C:\Users\h44z\Downloads\seaf-php\seaf-php\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 51

Somehow guzzle tries to open the file in read mode...

**Comment by rene-s** [comment]
Hello h44z,

OK I see, don't understand why this happens though. At first glance this rather looks like a bug in Guzzle.

I will pull the Share code if you remove the fopen() issue so we can treat both topics separately, thanks.

Regards
Rene

**Comment by h44z** [comment]
Yeah that is indeed a strange problem. Maybe it is related to windows - haven't tested the code on linux yet.

I will remove the code for the fopen issue soon, so you can pull the request.

**Comment by rene-s** [comment]
OK great, looking forward to it!

**Comment by rene-s** [comment]
Closing expired PR.

**Pull request closed without merging**
