### PR TITLE
feature: 1) share a library to users 2) return full response in a function

### PR DESCRIPTION
**Pull request by turtlegood**
feature:

* share a library to users
* return full response in a function

### CODE REVIEW

**Comment by rene-s** [comment]
Hello, thanks for the PR. Please split up the PR. I am OK with 16580bb but c5bfac1 I would like to have changed.

Instead of returning a boolean and accessing the response body by reference I would rather have the method return the full Response object.

Regards
Rene

**Comment by turtlegood** [comment]
@rene-s OK. So should I just create two PRs, or I just committed the 3rd time to implenent *return full response*?

**Comment by rene-s** [comment]
Hello, 2 PRs would suffice, thanks.

**Comment by turtlegood** [comment]
I cannot fully follow you. I guess you mean that I should give one PR for `share a library to users`. Am I right?
So should I create a new PR(and branch) and close this one or do in other ways?
Thanks.

**Comment by turtlegood** [comment]
@rene-s I have opened another pull request with only the library share function.

**Pull request closed without merging**
